name: ZombieRun
version: 0.1
main: com.apzombies.zombierun.ZombieRunMain
description: Zombie Run Minigame
commands:
  setmapspawn:
    description: Set the spawn for a ZombieRun map
  zrkit:
    description: Choose a kit, any kit